# Generated by Django 4.1.3 on 2023-02-01 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_bitrix24', '0002_isbitrix_delete_lead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='isbitrix',
            options={'managed': True, 'verbose_name': 'Интеграционная таблица bitrix', 'verbose_name_plural': 'Интеграционная таблица bitrix'},
        ),
    ]
