# Generated by Django 4.1.1 on 2023-02-08 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_listpeoplemodel_boss_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpeoplemodel',
            name='boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listbossmodel', verbose_name='id boss'),
        ),
    ]
