# Generated by Django 4.1.1 on 2023-02-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_usersmodel_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpeoplemodel',
            name='boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listbossmodel', verbose_name='id boss'),
        ),
    ]
