# Generated by Django 4.1.1 on 2023-02-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_listpeoplemodel_boss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='boss_id',
        ),
    ]
