# Generated by Django 4.1.1 on 2023-02-09 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_usersmodel_boss_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listbossmodel', verbose_name='id boss'),
        ),
    ]
