version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
      - minio
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_HOSTNAME=postgres
      - ENDPOINT_URL=http://minio:9000
      - PUBLIC_ENDPOINT_URL=http://localhost:9000
      - ACCESS_KEY=minioadmin
      - SECRET_KEY_S3=minioadmin
      - BUCKET_NAME=test
    env_file:
      - .env

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=postgres
#    env_file:
#      - ./app/.env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"

volumes:
  postgres-db:
  minio-data:
