# Generated by Django 4.1.3 on 2023-04-07 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0003_alter_isbitrix_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsBitrix',
        ),
    ]
