# Generated by Django 4.1.1 on 2023-02-08 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpeoplemodel',
            name='boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listbossmodel', verbose_name='d boss'),
        ),
    ]
