# Generated by Django 4.1.1 on 2023-02-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_listpeoplemodel_boss_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpeoplemodel',
            name='friendliness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Доброжелательный'),
        ),
        migrations.AlterField(
            model_name='listpeoplemodel',
            name='responsiveness',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Отзывчивый'),
        ),
    ]
