# Generated by Django 4.1.1 on 2023-02-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_listpeoplemodel_friendliness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listpeoplemodel',
            name='boss_id',
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='boss_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listbossmodel', verbose_name='id boss'),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listpeoplemodel', verbose_name='id user'),
        ),
    ]
