# Generated by Django 4.1.1 on 2023-02-08 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_listpeoplemodel_boss_id_usersmodel_boss_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.listpeoplemodel', verbose_name='id user'),
        ),
    ]
