# Generated by Django 4.1.3 on 2023-01-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('is_allur', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='isallur',
            table='is_allur',
        ),
    ]
