# Generated by Django 4.1.1 on 2023-02-08 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_listpeoplemodel_friendliness_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpeoplemodel',
            name='friendliness',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Доброжелательный'),
        ),
        migrations.AlterField(
            model_name='listpeoplemodel',
            name='responsiveness',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0, verbose_name='Отзывчивый'),
        ),
    ]
