version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "1020:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis