# Generated by Django 4.1.1 on 2023-02-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListBossModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('dep', models.CharField(blank=True, max_length=200, null=True, verbose_name='Департамент')),
            ],
            options={
                'verbose_name': 'Таблица боссов',
                'verbose_name_plural': 'Таблица боссов',
                'db_table': 'boss_list_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListPeopleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО')),
                ('dep', models.CharField(blank=True, max_length=200, null=True, verbose_name='Департамент')),
                ('responsiveness', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Отзывчивый')),
                ('friendliness', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Доброжелательный')),
            ],
            options={
                'verbose_name': 'Таблица сотрудников',
                'verbose_name_plural': 'Таблица сотрудников',
                'db_table': 'people_list_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Логин')),
                ('password', models.CharField(blank=True, max_length=200, null=True, verbose_name='Пароль')),
                ('timeInput', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего входа')),
                ('timeAuthEdit', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата изменения пароля')),
                ('isVoted', models.BooleanField(blank=True, default=True, null=True, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Таблица пользователей',
                'verbose_name_plural': 'Таблица пользователей',
                'db_table': 'ligin_user_model',
                'managed': True,
            },
        ),
    ]
