# Generated by Django 4.1.1 on 2023-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_usersmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
