# Generated by Django 4.1.3 on 2023-03-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=55)),
                ('lead_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_from_partner', models.JSONField(default=dict, verbose_name='Сам отправленный запрос')),
            ],
        ),
    ]
