# Generated by Django 4.1.3 on 2023-03-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allur', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lead_id',
        ),
        migrations.AddField(
            model_name='lead',
            name='app_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='client_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='documents_sent_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_id_on_bs',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
