# Generated by Django 4.1.1 on 2023-01-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadId', models.CharField(max_length=20)),
                ('applicationId', models.CharField(max_length=20)),
                ('clientId', models.CharField(max_length=20)),
                ('jsonRequest', models.JSONField(default='{}')),
                ('timeCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
